---

- name: Add smokeping user
  user: name=smokeping home=/opt/smokeping system=yes
  tags:
    - smokeping
    - users

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Download smokeping
  get_url: url={{ smokeping_url }} dest=/tmp/smokeping.tar.gz
  tags:
    - smokeping

- name: extract smokeping
  unarchive: src=/tmp/smokeping.tar.gz dest=/opt/ copy=no
  tags:
    - smokeping

- command: /opt/smokeping-2.6.11/configure --prefix=/opt/smokeping
- command: /opt/smokeping-2.6.11/make install

- name: Make required directories
  file: path={{ item }} state=directory
  with_items:
    - /opt/smokeping/data
    - /opt/smokeping/var
    - /opt/smokeping/cache
  tags:
    - smokeping-build

# build here
# - command: /opt/smokeping-2.6.11/setup/build-perl-modules.sh /opt/smokeping/thirdparty
# set $PERL5LIB to /opt/smokeping/thirdparty
