---

- hosts: mysql-server
  sudo: True

  roles:
    - common
    - mysql-server

- hosts: postgre-server
  sudo: True

  roles:
    - common
    - postgresql

- hosts: postgre-master
  sudo: True

  roles:
    - postgresql-replication-master

- hosts: postgre-slave
  sudo: True

  roles:
    - postgresql-replication-slave
