---

- hosts: sensu-master
  sudo: True

  roles:
    - sensu-server

- hosts: graphite
  sudo: True

  roles:
    - graphite

- hosts: grafana
  sudo: True

  roles:
    - grafana

- hosts: graylog2
  sudo: True

  roles:
    - graylog2
