---

# talk to all hosts just so we can learn about them
# https://docs.ansible.com/playbooks_best_practices.html#operating-system-and-distribution-variance
#- hosts: all
#  tasks:
#     - group_by: key=os_{{ ansible_distribution }}

- include: initial.yml
- include: common.yml
- include: auth.yml
- include: openvpn.yml
- include: db.yml
- include: dns.yml
- include: applications.yml
- include: monitoring.yml

- hosts: smokeping-build
  sudo: True

  roles:
    - smokeping-build

- hosts: yum-repo
  sudo: True

  roles:
    - yum-repo
