---

# talk to all hosts just so we can learn about them
# https://docs.ansible.com/playbooks_best_practices.html#operating-system-and-distribution-variance
#- hosts: all
#  tasks:
#     - group_by: key=os_{{ ansible_distribution }}

- include: initial.yml
- include: common.yml
- include: auth.yml
- include: openvpn.yml
- include: mojibake.yml
- include: sensu-master.yml
- include: db.yml
- include: xbmc.yml
- include: dns.yml
