---

- name: Check if httpd can network_connect SEBoolean is set
  command: "sestatus -b | grep 'httpd_can_network_connect ' | awk '{print $2}'"
  register: httpd_boolean

- name: Allow httpd to connect to network ports (so we can proxy kibana)
  command: setsebool -P httpd_can_network_connect 1
  when: httpd_boolean.stdout == 'off'

- name: Install kibana Apache config file
  template: src=kibana.conf.j2 dest=/etc/httpd/conf.d/kibana.conf
  notify: restart httpd

- name: Add acl to allow logstash to read yum log file
  acl: name=/var/log/yum.log entity=logstash etype=group
       permissions="r" state=present
