---

- name: check firewalld installed
  stat: path=/usr/lib/systemd/system/firewalld.service get_md5=no
  register: firewalld_installed

- name: Allow http through the firewall
  firewalld: service=http permanent=true state=enabled
  notify: restart firewalld

- name: Allow https through the firewall
  firewalld: service=https permanent=true state=enabled
  notify: restart firewalld
  when: ssl == true
