---

- name: Get the plugins
  get_url: url={{ item.value.url }}
           dest=/etc/sensu/plugins/{{ item.value.file }}
           owner=sensu
           group=sensu
           mode=0744
  with_dict: checks
  notify: restart sensu-client

- name: Install check on master
  template: src=check.json.j2 dest=/etc/sensu/conf.d/{{ item.key }}.json
  with_dict: checks
  delegate_to: virt01
  notify: restart sensu-server
