---

- name: restart rabbitmq
  service: name=rabbitmq-server state=restarted

- name: restart sensu
  service: name={{ item }} state=restarted
  with_items:
    - sensu-server
    - sensu-client
    - sensu-api
