---

- name: restart nginx
  service: name=nginx state=restarted

# - name: restart supervisord
#   service: name=supervisord state=restarted

- name: daemon-reload
  command: /bin/systemctl daemon-reload

