---

- name: install bind
  yum: name=bind state=present

# Copy config

- name: Allow http through the firewall
  firewalld: service=dns permanent=true state=enabled
  notify: restart firewalld

- name: Start and enable bind (named)
  service: name=named state=started enabled=yes

