---

- name: install package requirements
  yum: name={{ item }} state=present
  with_items:
    - autoconf
    - automake
    - expect
    - gcc
    - glibc-devel
    - gnutls-devel
    - libident-devel
    - make
    - pam-devel
    - tcp_wrappers-devel
    - telnet
    - zlib-devel
    - openssl-devel
    - rpmbuild
    - rpm-sign

# install rpmbuild, rpm-sign

- name: add rpmbuild users
  user: name=rpmbuild
  tags:
    - ngircd-build
    - build-user

- name: download ngircd
  get_url: url={{ download_url }} dest=/home/rpmbuild/ngircd.tar.gz
  tags:
    - ngircd-build

- name: download ngircd
  unarchive: src=/home/rpmbuild/ngircd.tar.gz dest=/home/rpmbuild/ircd copy=no
  tags:
    - ngircd-build

- name: configure ngircd as rpmbuild
  shell: "/home/rpmbuild/ircd/ngircd-22.1/configure --prefix= --with-openssl --enable-ipv6 --with-syslog --with-zlib"
  sudo_user: rpmbuild
  tags:
    - ngircd-build

- name: make ngircd as rpmbuild
  shell: "/home/rpmbuild/ircd/ngircd-22.1/make"
  sudo_user: rpmbuild
  tags:
    - ngircd-build

- name: make install ngircd as rpmbuild
  shell: "/home/rpmbuild/ircd/ngircd-22.1/make install DESTDIR=/home/rpmbuild/ircd/build" # make install DESTDIR=/tmp/project install
  sudo_user: rpmbuild
  tags:
    - ngircd-build

- replace: dest=/home/rpmbild/ircd/build/etc/ngircd.conf
           regexp="/home/rpmbuild/ircd/build/share/*"
           replace=":DOCDIR:"

- replace: dest=/home/rpmbild/ircd/build/etc/ngircd.conf
           regexp="/home/rpmbuild/ircd/build/etc/*"
           replace=":ETCDIR:"

- lineinfile: dest=/home/rpmbild/ircd/build/etc/ngircd.conf
              state=present
              regexp="^;ServerGID ="
              line="ServerGID = ngircd"

- lineinfile: dest=/home/rpmbild/ircd/build/etc/ngircd.conf
              state=present
              regexp="^;ServerUID ="
              line="ServerUID = ngircd"

- name: create our systemd service dir
  file: path=/home/rpmbild/ircd/build/etc/systemd/system/ state=directory

- name: copy across post-install file
  copy: src=../files/post-install.sh dest=/home/rpmbild/ircd/post-install.sh
        owner=rpmbuild group=rpmbuild mode=0660

- name: copy across mojibake settings file
  copy: src=../files/ngircd.service
        dest=/home/rpmbild/ircd/build/usr/lib/systemd/system/ngircd.service
        owner=rpmbuild group=rpmbuild mode=0660
  tags:
    - mojibake

# fpm -s dir -t rpm -C /home/rpmbuild/ircd/build --name ngircd --version 22.1 --iteration 1 --description "Next Generation IRC Daemon" --after-install post-install.sh

# - name: delete rpmbuild user
#   user: name=rpmbuild state=absent remove=yes
#   tags:
#     - ngircd-build
#     - build-user
