---

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create replication db user/password
  postgresql_user: name=rep
                   password={{ replication_db_pass }}
                   role_attr_flags=REPLICATION,LOGIN
                   state=present
  tags:
    - postgresql-replication
    - db

- name: make postgres ssh directory
  file: path=/var/lib/pgsql/.ssh state=directory owner=postgres group=postgres mode=0700

- name: add postgres user to ssh_users
  user: name=postgres groups=ssh_users append=yes
  tags:
    - postgresql-replication
    - users

# - name: check if ssh key exists
#   stat: path=/var/lib/pgsql/.ssh/id_rsa get_md5=no
#   register: key_exists

# - name: Creating new SSH key pair for postgres
#   command: ssh-keygen -t rsa -b 2048 -N '' -q -f /var/lib/pgsql/.ssh/id_rsa -C "PostgreSQL Replication SSH Key"
#   when: key_exists.stat.isreg is undefined or (key_exists.stat.isreg) == false

# - name: ensure ownership is correct
#   file:
#     path: /var/lib/pgsql/.ssh/
#     mode: "u=rwX,g-rX,o-rX"
#     owner: postgres
#     group: postgres
#     recurse: yes

# - name: ensure ownership is correct
#   file:
#     path: "{{ item }}"
#     mode: 0600
#     owner: postgres
#     group: postgres
#   with_items:
#     - /var/lib/pgsql/.ssh/id_rsa
#     - /var/lib/pgsql/.ssh/id_rsa.pub

# - name: Download postgres pub key
#   fetch: src=/var/lib/pgsql/.ssh/id_rsa.pub dest=/tmp/postgres-pub.tmp flat=yes
