---

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create replication db user/password
  postgresql_user: name=rep
                   password={{ replication_db_pass }}
                   role_attr_flags=REPLICATION,LOGIN
                   state=present
  tags:
    - postgresql-replication
    - db

- name: make postgres ssh directory
  file: path=/var/lib/pgsql/.ssh state=directory owner=postgres group=postgres mode=0700

- name: add postgres user to ssh_users
  user: name=postgres groups=ssh_users append=yes
  tags:
    - postgresql-replication
    - users

- name: add requires lines to postgresql.conf
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              regexp="^{{ item.key }}"
              line="{{ item.value }}"
              state=present
              backrefs=yes
  with_items:
    - { key: '#wal_level = minimal', value: 'wal_level = hot_standby' }
    - { key: '#archive_mode = off', value: 'archive_mode = on'}
    - { key: '#archive_command = ''', value: "archive_command = 'cd .'"}
    - { key: '#max_wal_senders = 0', value: 'max_wal_senders = 1'}
    - { key: '#hot_standby = off', value: 'hot_standby = on'}
    - { key: "#listen_addresses = 'localhost'", value: "listen_addresses = 'localhost,{{ ansible_default_ipv4.address }}'"}
