---

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create replication db user/password
  postgresql_user: name=rep
                   password={{ replication_db_pass }}
                   role_attr_flags=REPLICATION,LOGIN
                   state=present
  tags:
    - postgresql-replication
    - db

- name: make postgres ssh directory
  file: path=/var/lib/pgsql/.ssh state=directory owner=postgres group=postgres mode=0700

- name: add postgres user to ssh_users
  user: name=postgres groups=ssh_users append=yes
  tags:
    - postgresql-replication
    - users
