---

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create replication db user/password
  postgresql_user: name=rep
                   password={{ replication_db_pass }}
                   role_attr_flags=REPLICATION,LOGIN
                   state=present
  tags:
    - postgresql-replication
    - db

- name: make postgres ssh directory
  file: path=/var/lib/pgsql/.ssh state=directory owner=postgres group=postgres mode=0700

- name: add postgres user to ssh_users
  user: name=postgres groups=ssh_users append=yes
  tags:
    - postgresql-replication
    - users

- name: add in wal_level to postgresql.conf
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              regexp='^#wal_level = minimal'
              line='wal_level = hot_standby'
              state=present
              backrefs=yes

- name: add in wal_level to postgresql.conf
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              regexp='^#archive_mode = off'
              line='archive_mode = on'
              state=present
              backrefs=yes

- name: add in wal_level to postgresql.conf
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              regexp='^#archive_command = '''
              line="archive_command = 'cd .'"
              state=present
              backrefs=yes

- name: add in wal_level to postgresql.conf
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              regexp='^#max_wal_senders = 0'
              line='max_wal_senders = 1'
              state=present
              backrefs=yes

- name: add in wal_level to postgresql.conf
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              regexp='^#hot_standby = off'
              line='hot_standby = on'
              state=present
              backrefs=yes

- name: add in wal_level to postgresql.conf
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              regexp="^#listen_addresses = 'localhost'"
              line="listen_addresses = 'localhost,{{ ansible_default_ipv4.address }}'"
              state=present
              backrefs=yes

