---

- name: Install graphite dashboard
  yum: name={{ item }} state=present
  with_items:
    - graphite-web
    - python-carbon
    - python-whisper

- name: Move across graphite-web apache config (overwrites default)
  template: src=graphite-web.conf.j2 dest=/etc/httpd/conf.d/graphite-web.conf
  notify: restart httpd

- name: Install graphite-web settings
  template: src=local_settings.py.j2 dest=/etc/graphite-web/local_settings.py

- name: check to see if graphite db exists
  stat: path=/var/lib/graphite-web/graphite.db
  register: graphite_db

- name: Copy across django password generator
  copy: src=../files/generate_hashed_password.py dest=/var/lib/graphite-web/generate_hashed_password.py
  when: graphite_db.stat.exists == False

- name: Generate encrypted password
  command: python /var/lib/graphite-web/generate_hashed_password.py {{ superuser_password }}
  register: encrypted_superuser_pass
  when: graphite_db.stat.exists == False

# In Django 1.7 and onwards syncdb is deprecated and replaced by migrate
# https://docs.djangoproject.com/en/1.7/ref/django-admin/#syncdb
- name: create db
  command: django-admin syncdb --settings=graphite.settings --noinput
  when: graphite_db.stat.exists == False

- name: Install graphite-web settings
  template: src=initial_data.json.j2 dest=/var/lib/graphite-web/initial_data.json
  when: graphite_db.stat.exists == False

- name: merge in initial user data to graphite db
  command: django-admin loaddata --settings=graphite.settings /var/lib/graphite-web/initial_data.json
  when: graphite_db.stat.exists == False

- name: Delete the initial user data file we uploaded
  file: path=/var/lib/graphite-web/initial_data.json state=absent

- name: Delete the password generator python script we uploaded
  file: path=/var/lib/graphite-web/generate_hashed_password.py state=absent

- name: ensure ownership of db by apache
  file: path=/var/lib/graphite-web/graphite.db owner=apache group=apache
