---

# Management IPs or hosts, will be put in the fail2ban ssh.local jail config
# file as IP address to be ignored, i.e. not banned if too many login failures
# are made
# "ignoreip" can be an IP address, a CIDR mask or a DNS host
management_ips:
  -
