---

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: make /var/mojibake
  file: path=/var/mojibake state=directory
  tags:
    - docker_logging

- name: Pull down Docker compose file
  get_url:
    url="https://raw.githubusercontent.com/ardinor/dockerfiles/master/Compose%20files/logstash-logspout/docker-compose.yml"
    dest="/var/logging/docker-compose.yml"
    mode=0400
  when: docker_logging == true
  tags:
    - docker_logging

- name: Start logspout and logstash containers
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: /var/logging/
  when: docker_logging == true
  environment: compose_env
  tags:
    - docker_logging
