---

- name: Import elasticsearch repo signing key
  command: rpm --import https://packages.elasticsearch.org/GPG-KEY-elasticsearch
  tags:
    - elasticsearch
    - gpg-key

- name: Install elasticsearch repo
  copy: src=../files/elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo
  tags:
    - elasticsearch
    - repo

- name: Install elasticsearch
  yum: name=elasticsearch state=present
  tags:
    - elasticsearch
    - packages
