---

- name: Install xbmc (kodi)
  yum: name=kodi state=latest
  tags:
    - xbmc
    - packages

- name: Install advancedsettings config file
  template: src=advancedsettings.xml.j2 dest=/usr/share/kodi/userdata/advancedsettings.xml
  tags:
    - xbmc
    - config_files
