---

- name: add www-data user
  user: name=www-data system=yes state=present

- name: make /var/www
  file: path=/var/www state=directory owner=www-data group=www-data mode=0755

- name: Install nginx repo
  yum: name={{ nginx_rpm_url }} state=present

- name: Install nginx
  yum: name=nginx state=latest

- name: Enable nginx service
  service: name=nginx enabled=yes

- name: Make sites-available directory
  file: path=/etc/nginx/sites-available state=directory

- name: Make sites-enabled directory
  file: path=/etc/nginx/sites-enabled state=directory

# Check mode on these files, need to specify it?
# Does this really need to be a template?
- name: Install main nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Install site config file
  template: src=site.conf.j2 dest=/etc/nginx/sites-available/site.conf

- name: Link site config to sites-enabled
  file: src=/etc/nginx/sites-available/site.conf dest=/etc/nginx/sites-enabled/site.conf
        state=link
  notify: restart nginx

- name: Allow http through the firewall
  firewalld: service=http permanent=true state=enabled

- name: Allow https through the firewall
  firewalld: service=https permanent=true state=enabled
