---

- name: add www-data user
  user: name=www-data system=yes state=present

- name: make /var/www
  file: path=/var/www state=directory owner=www-data group=www-data mode=0755

- name: Install nginx repo
  yum: name={{ nginx_rpm_url }} state=present

- name: Install nginx
  yum: name=nginx state=latest

- name: Make required directories
  file: path={{ item }} state=directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
    - "{{ site_directory }}"
    - "{{ site_log_directory }}"

# Check mode on these files, need to specify it?
# Does this really need to be a template?
- name: Install main nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Install SSL site config file
  template: src=ssl_site.conf.j2 dest=/etc/nginx/sites-available/site.conf
  when: ssl == true

- name: Install site config file
  template: src=site.conf.j2 dest=/etc/nginx/sites-available/site.conf
  when: ssl == false

- name: Link site config to sites-enabled
  file: src=/etc/nginx/sites-available/site.conf dest=/etc/nginx/sites-enabled/site.conf
        state=link
  notify: restart nginx

- name: start nginx and ensure enabled=yes
  service: name=nginx state=started enabled=yes

- name: Allow http through the firewall
  firewalld: service=http permanent=true state=enabled
  notify: restart firewalld

- name: Allow https through the firewall
  firewalld: service=https permanent=true state=enabled
  notify: restart firewalld
  when: ssl == true
