- hosts: web
  sudo: yes

  tasks:
    - name: Install nginx repo
      yum: name="{{ nginx-rpm-url }}" state=present

    - name: Install nginx
      yum: name=nginx state=latest

    - name: Enable nginx service
      service: name=nginx enabled=yes

    # config goes here

    - name: Allow http through the firewall
      firewalld: service=http permanent=true state=enabled

    - name: Allow https through the firewall
      firewalld: service=https permanent=true state=enabled
